### PR TITLE
Update for stack lts-11.4 with some TH CPP logic.

### PR DESCRIPTION
**Pull request by christian-marie**
Fixed some stuff.

Is required = [ "field1", "field2" ] unsupported?

### CODE REVIEW

**Comment by christian-marie** [comment]
Bonus: discovered today that there seems to be one too many apostrophes on Array

**Comment by christian-marie** [comment]
@Fuuzetsu feel free to add me as a maintainer on this repo and hackage if you want help.

**Comment by Fuuzetsu** [comment]
@christian-marie I'd be happy to, I've had this (or the other update PR) sitting in pinned tab since it was opened, just didn't get around to merging/testing it as I haven't used the package myself for yours... What's your hackage username?

I'd like you to reconcile this PR with #11 which updates to newer LTS. Preferably newer is better.

**Comment by Fuuzetsu** [comment]
I added you on GitHub and Hackage.

**Comment by christian-marie** [comment]
Thanks. They're almost the same, I'll just take the latter.

**Pull request closed without merging**
