### PR TITLE
upd bounds, fixed MonadFail compat issues with some CPP

### PR DESCRIPTION
**Pull request by ocramz**
* Increased upper dependency bounds for compat with Stackage nightly 30/12/2019 (GHC 8.8.1)
* added some CPP conditionals to account for newer dependencies (`text` and `regex-pcre`)
* sorted dependencies

### CODE REVIEW

**Comment by ocramz** [comment]
Unfortunately the TravisCI build fails due to a configuration error unrelated to this PR: 

```
hint-0.8.0 failed during the building phase. The exception was:

ExitFailure 1

The command "if diff -u $HOME/.cabsnap/installplan.txt installplan.txt; then echo "cabal build-cache HIT"; rm -rfv .ghc; cp -a $HOME/.cabsnap/ghc $HOME/.ghc; cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/; else echo "cabal build-cache MISS"; rm -rf $HOME/.cabsnap; mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin; cabal install --only-dependencies --enable-tests --enable-benchmarks; fi" failed and exited with 1 during .
```

**Comment by Fuuzetsu** [comment]
I updated travis a little. I couldn't get this branch to build on top of any of the GHC versions it says it was tested with. Please generate new travis file and try yourself. After you apply the patch in this MR, you should be able to run `haskell-ci aeson-schema.cabal --submodules --no-run-tests`, commit and push then watch what Travis says.

I don't mind dropping old GHC versions if that makes it easier for you FWIW. Maybe 8.2 and onwards is enough.

**Comment by ocramz** [comment]
In a hurry, I commented out the test parts in the Cabal file while developing the patch; the library compiles as intended up to GHC 8.10 . 
I don't use Cabal directly BTW, only stack, and it was enough to say

```
git submodule init
git submodule update
stack build
```

Now I'm fixing the type signatures in `test` because they too are missing the MonadFail constraints. As soon as the tests run I'd be happy to help you with maintenance of this package and to release a new version.

**Comment by Fuuzetsu** [comment]
Hm, there's this package now: http://hackage.haskell.org/package/aeson-schemas

I wonder if it's just better and we should all use that?

**Comment by Fuuzetsu** [comment]
I added you on hackage and sent invite on github, feel free to do any updates &c.

**Comment by AlexeyRaga** [comment]
Any progress on this issue?
I see that only ancient versions of GHC are problematic now, maybe can be just deprecated?

**Comment by Fuuzetsu** [comment]
I don't mind that, if you send a
patch then I'd be happy to take it

**Comment by nikita-volkov** [comment]
Can this please be merged? The package is unusable with modern GHC versions.

**Pull request merged**
